Donatsi/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import  static
from . import settings
from .views import homepage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homepage, name="homepage"), #homepage ntar
    path('tentang-kami/', include("TentangKami.urls", namespace="tentang-kami")),
    path('donasi/', include("PermohonanDonasi.urls", namespace="permohonan")),
    path('donasi/', include("PemberianDonasi.urls", namespace="pemberian")),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

PemberianDonasi/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import daftar_pemberian

app_name = "pemberian"
urlpatterns = [
    path('<id>/beri-donasi', daftar_pemberian, name="daftar_pemberian"),
]

PermohonanDonasi/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import daftar_permohonan, list_permohonan, detail_permohonan

app_name = "permohonan"
urlpatterns = [
    path('', list_permohonan, name="list-permohonan"),
    path('<id>', detail_permohonan, name="detail-permohonan"),
    path('daftar/', daftar_permohonan, name="daftar-permohonan")
]

TentangKami/urls.py
from django.urls import path, include
from .views import tentang_kami

app_name = "tentang-kami"
urlpatterns = [
    path('', tentang_kami, name="about")
]

templates/base-template.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static  'base.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
	<script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
    <link rel="stylesheet" href="{% static 'style.css' %}" />
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    {% block styling %}{% endblock %}
	<link rel="stylesheet" href="https://m.w3newbie.com/you-tube.css">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <nav id="navbar" class="navbar navbar-expand-md navbar-light bg-light sticky-top">
        <div class="container">
            <a class="navbar-brand" href="{% url 'homepage' %}"><img id="logonavbar" class="logo" src="{% static 'donatsibiru.png' %}"></a>
    
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
                <span class="navbar-toggler-icon"></span>
            </button>
    
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
    
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'homepage' %}">Recommendations</a>
                    </li>
    
                    <li class="nav-item">
                            <a class="nav-link" href="{% url 'tentang-kami:about' %}">About Us</a>
                        </li>
    
                    <li class="nav-item">
                            <a class="nav-link" href="{% url 'permohonan:list-permohonan' %}">All Donations</a>
                        </li>
                    
                    <li class="nav-item">
                            <a class="nav-link" href="{% url 'permohonan:daftar-permohonan' %}">Open Donations</a>
                        </li>
                </ul>
                
            </div>
        </div>
    </nav>
    {% block content %}
    {% endblock %}
</body>
</html>

templates/homepage.html
{% extends 'base-template.html' %}
{% load static %}
{% block title %}
Donatsi
{% endblock %}

{% block content %}

<!-- Opening -->
<div id="rc_opening">
    <div class="center">
        <img id="rc_logo" src = "{% static 'donatsi.png' %}">
    </div>
            
    <div class="center">
        <h6 id="rct_judul"> Donatsi adalah Lorem ipsum, atau ringkasnya lipsum, adalah teks standar yang ditempatkan untuk mendemostrasikan elemen grafis 
        atau presentasi visual seperti font, tipografi, dan tata letak. Maksud penggunaan lipsum adalah agar pengamat tidak terlalu 
        berkonsentrasi kepada arti harfiah per kalimat, melainkan lebih kepada elemen desain dari teks yang dipresentasi.</h6>
    </div>
            
    <div class="center">
        <img id="rc_vector" src = "{% static 'vector.png' %}">
    </div>

<!-- Form -->
<div class="center">
    <h3 id="rct_form"> Ingin Berdonasi? </h3>
    </div>
    
    <div class="center" id = "rc_form">
        <form method="GET" action="{% url 'permohonan:list-permohonan' %}">
            <input class="form-control" type="text" name="query" placeholder="cari donasi...">
            <div class="center" id="rc_button">
                <input class="submit" type="submit" value="Search">
            </div>
        </form>
    </div>
    
</div>

<div id="rc_formcard">
    {% if recommendations %}
    <div class="card-group row" id="rc_cardcontainer">
        {% for permohonan in recommendations %}
            <div class="col-xl-3 col-md-4 col-12" id="rc_donations">
                <div class="card h-100">
                    <img class="card-img-top" src="{{ permohonan.image_donasi.url }}" alt="image">
                    <div class="card-body">
                        <h4 class="card-title">{{ permohonan.nama_donasi }}</h4>
                        <p class="card-text">Kategori: {{ permohonan.kategori_alasan }}</p>
                        <p class="card-text">Deskripsi: {{ permohonan.deskripsi_singkat }}</p>
                        <h5 class="card-text duit">Rp. {{ permohonan.uang_terpenuhi }} / Rp. {{ permohonan.target_uang }}</h5>
                        <p class="card-text">Deadline: {{ permohonan.deadline }}</p>
                        <a href="{% url 'pemberian:daftar_pemberian' id=permohonan.id %}"><button class="submit">Donate</button></a>
                        <a href="{% url 'permohonan:detail-permohonan' id=permohonan.id %}"><p id="details" class="permohonan-details">Details</p></a>            
                    </div>
            </div>
            </div>
        {% endfor %}
    </div>
    {% endif %}

{% endblock %}
</div>